import {describe,it,expect} from 'vitest';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {Store} from '../src/storage/database.js';
import {SyncWorker,type DiscordSource} from '../src/discord/sync.js';
import type {SourceMessage} from '../src/core/types.js';
import {createApp} from '../src/server/app.js';
import {setPassword} from '../src/auth/password.js';

const message=(id:string,overrides:Partial<SourceMessage>={}):SourceMessage=>({id,channelId:'3',createdAt:'2025-01-01T00:00:00.000Z',editedAt:null,authorId:'5',authorBot:false,webhookId:null,content:'strategy',attachments:[],...overrides});
const config={includedCategoryIds:new Set(['2']),excludedChannelIds:new Set<string>()};
const setup=async()=>{const dir=await mkdtemp(join(tmpdir(),'playbook-regression-'));const store=new Store(join(dir,'db.sqlite'));let categories=[{id:'2',name:'Cat',position:0}];let channels:{id:string;categoryId:string|null;name:string;position:number}[]=[{id:'3',categoryId:'2',name:'guide',position:0}];let messages=[message('1')];const api:DiscordSource={guild:async()=>({id:'9',name:'Guild'}),categories:async()=>categories,channels:async()=>channels,history:async()=>messages,message:async()=>null};const worker=new SyncWorker(api,store,{save:async()=>{throw new Error('media should not be downloaded');}} as any,config,()=>{},0);return {dir,store,worker,set categories(x:{id:string;name:string;position:number}[]){categories=x;},set channels(x:{id:string;categoryId:string|null;name:string;position:number}[]){channels=x;},set messages(x:SourceMessage[]){messages=x;}};};

describe('review finding regressions',()=>{
 it('revokes confirmed out-of-scope strategies before reporting a missing category',async()=>{const f=await setup();try{f.store.publish({id:'3',categoryId:'2',available:true,syncStatus:'current',steps:[],revision:'a'.repeat(64)});f.categories=[];f.channels=[{id:'3',categoryId:null,name:'guide',position:0}];await expect(f.worker.reconcile()).rejects.toThrow('category IDs');expect(f.store.getStrategy('3')).toBeNull();}finally{f.store.close();}});
 it('does not process ignored bot or webhook attachments and clears unchanged sync status',async()=>{const f=await setup();try{f.messages=[message('1'),message('2',{authorBot:true,attachments:[{id:'ignored',filename:'bad.png',contentType:'image/png',size:1,url:'https://example.invalid/bad.png'}]})];f.worker.enqueue('3');await f.worker.runDue();expect(f.store.getStrategy('3').sourceMessages.map((m:SourceMessage)=>m.id)).toEqual(['1']);f.worker.enqueue('3');expect(f.store.getStrategy('3').syncStatus).toBe('stale');await f.worker.runDue();expect(f.store.getStrategy('3').syncStatus).toBe('current');}finally{f.store.close();}});
 it('keeps a successful sync stale when a newer event was queued in flight',async()=>{const f=await setup();try{let release!:()=>void;let entered!:()=>void;const waiting=new Promise<void>(r=>release=r);const started=new Promise<void>(r=>entered=r);const api:DiscordSource={guild:async()=>({id:'9',name:'Guild'}),categories:async()=>[],channels:async()=>[{id:'3',categoryId:'2',name:'guide',position:0}],history:async()=>{entered();await waiting;return [message('1')];},message:async()=>null};const worker=new SyncWorker(api,f.store,{save:async()=>{}} as any,config,()=>{},0);worker.enqueue('3');const sync=worker.runDue();await started;worker.enqueue('3');release();await sync;expect(f.store.getStrategy('3').syncStatus).toBe('stale');}finally{f.store.close();}});
 it('reserves login attempts before concurrent password verification',async()=>{const f=await setup();const passwordFile=join(f.dir,'password.json');await setPassword(passwordFile,'fixture password long enough');const server=createServer(createApp({store:f.store,media:{} as any,passwordFile,sessionSecret:'test-session-secret-'.padEnd(32,'x')}));await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw new Error('No HTTP address');const base=`http://127.0.0.1:${address.port}`;try{const responses=await Promise.all(Array.from({length:25},()=>fetch(`${base}/api/session`,{method:'POST',headers:{'content-type':'application/json',origin:base},body:JSON.stringify({password:'wrong password'})})));expect(responses.filter(r=>r.status===429).length).toBeGreaterThanOrEqual(5);expect(responses.filter(r=>r.status===401).length).toBeLessThanOrEqual(20);}finally{server.close();f.store.close();}});
});
