import {Client,GatewayIntentBits,Partials,ChannelType,Message} from 'discord.js';import type {SourceMessage} from '../core/types.js';import type {DiscordSource} from './sync.js';
export class DiscordClient implements DiscordSource {readonly client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent],partials:[Partials.Channel,Partials.Message,Partials.GuildMember]});constructor(private guildId:string){}
 async start(token:string){await this.client.login(token);await this.guild();}
 async guild(){const guild=this.client.guilds.cache.get(this.guildId)??await this.client.guilds.fetch(this.guildId);return guild;}
 async categories(){const guild=await this.guild();const channels=await guild.channels.fetch();return [...channels.values()].filter((c):c is NonNullable<typeof c>=>!!c&&c.type===ChannelType.GuildCategory).map(c=>({id:c.id,name:c.name,position:c.position})).sort((a,b)=>a.position-b.position);}
 async channels(){const guild=await this.guild();const channels=await guild.channels.fetch();return [...channels.values()].filter(c=>!!c&&c.type===ChannelType.GuildText).map(c=>({id:c!.id,categoryId:c!.parentId,name:c!.name,position:c!.position})).sort((a,b)=>a.position-b.position);}
 async history(channelId:string){const guild=await this.guild();const channel=await guild.channels.fetch(channelId);if(!channel||channel.type!==ChannelType.GuildText)throw new Error('Configured strategy channel is not readable text');const found:SourceMessage[]=[];let before:string|undefined;while(true){const page=await channel.messages.fetch({limit:100,...(before?{before}:{})});if(page.size===0)break;found.push(...page.map(serialize));before=page.last()?.id;if(page.size<100)break;}return found;}
 async message(channelId:string,messageId:string){const guild=await this.guild();const channel=await guild.channels.fetch(channelId);if(!channel||channel.type!==ChannelType.GuildText)throw new Error('Channel unavailable');try{return serialize(await channel.messages.fetch({message:messageId,force:true}));}catch(error){if((error as any)?.code===10008)return null;throw error;}}
}
function serialize(m:Message):SourceMessage{return {id:m.id,channelId:m.channelId,createdAt:m.createdAt.toISOString(),editedAt:m.editedAt?.toISOString()??null,authorId:m.author.id,authorBot:m.author.bot,webhookId:m.webhookId,content:m.content,attachments:[...m.attachments.values()].map(a=>({id:a.id,filename:a.name??'attachment',contentType:a.contentType,size:a.size,url:a.url,description:a.description}))};}
