import {isEligibleMessage,projectStrategy} from '../core/projection.js';import type {SourceMessage} from '../core/types.js';import {inScope} from '../core/config.js';import {Store} from '../storage/database.js';import {MediaStore} from '../storage/media.js';
export interface DiscordSource {guild():Promise<{id:string;name:string}>;categories():Promise<{id:string;name:string;position:number}[]>;channels():Promise<{id:string;categoryId:string|null;name:string;position:number}[]>;history(channelId:string):Promise<SourceMessage[]>;message(channelId:string,messageId:string):Promise<SourceMessage|null>;}
export class SyncWorker {private running=new Set<string>();constructor(private api:DiscordSource,private store:Store,private media:MediaStore,private cfg:{includedCategoryIds:Set<string>;excludedChannelIds:Set<string>},private log=(event:string,data:Record<string,unknown>)=>console.info(JSON.stringify({event,...data})),private debounceMs=5000){}
 enqueue(id:string){this.store.enqueue(id,this.debounceMs);}
 async reconcile(){const [guild,categories,channels]=await Promise.all([this.api.guild(),this.api.categories(),this.api.channels()]);const knownCategories=new Set(categories.map(c=>c.id));const scope=new Set(channels.filter(c=>inScope(c,this.cfg)).map(c=>c.id));for(const old of this.store.listStrategies())if(!scope.has(old.id))this.unavailable(old.id);const invalid=[...this.cfg.includedCategoryIds].filter(id=>!knownCategories.has(id));if(invalid.length){this.log('invalid_category_ids',{count:invalid.length,ids:invalid});throw new Error('One or more configured category IDs are invalid or unreadable');}this.store.setMeta('guild',guild);this.store.setMeta('categories',categories.filter(c=>this.cfg.includedCategoryIds.has(c.id)));this.store.setMeta('lastSuccessfulReconciliation',new Date().toISOString());for(const channel of channels)if(scope.has(channel.id))this.enqueue(channel.id);this.log('reconcile',{categories:categories.length,channels:scope.size});}
 async runDue(){for(const row of this.store.due()){const id=row.channel_id;if(this.running.has(id))continue;this.running.add(id);try{const current=(await this.api.channels()).find(c=>c.id===id);if(!current||!inScope(current,this.cfg)){this.unavailable(id);this.store.done(id,row.generation);continue;}const messages=await this.api.history(id);const strategy=projectStrategy({channelId:id,categoryId:current.categoryId!,position:current.position,sourceName:current.name,messages});for(const source of messages.filter(isEligibleMessage)){for(const att of source.attachments){if(!/^image\//i.test(att.contentType??'')&&!/\.(png|jpe?g|webp|gif|bmp|tiff?)$/i.test(att.filename))continue;if(!/^image\/(png|jpeg|webp)$/i.test(att.contentType??'')&&!/\.(png|jpe?g|webp)$/i.test(att.filename)){strategy.warnings.push(`Unsupported image attachment: ${att.filename}`);continue;}if(!att.url)throw new Error(`Missing attachment URL for ${att.filename}`);const cached=this.store.mediaFor(att.id);const saved=cached&&await this.media.exists(cached.file)?cached:await this.media.save(att.url,att.contentType,att.filename);this.store.rememberMedia(att.id,saved);for(const sourceMessage of strategy.sourceMessages)for(const metadata of sourceMessage.attachments)if(metadata.id===att.id){metadata.width=saved.width;metadata.height=saved.height;metadata.contentHash=saved.hash;metadata.storageKey=`images/${saved.file}`;}strategy.steps.forEach(step=>step.images.forEach(image=>{if(image.attachmentId===att.id)image.file=`images/${saved.file}`;}));}}
 const existing=this.store.getStrategy(id);if(existing?.revision!==strategy.revision)this.store.publish(strategy);else strategy.publishedAt=existing.publishedAt;this.store.markSyncStatus(id,row.generation);this.store.setMeta('lastSuccessfulSync',new Date().toISOString());this.store.done(id,row.generation);this.log('publish',{channelId:id,revision:strategy.revision,changed:existing?.revision!==strategy.revision});}catch(error){const e=error as Error;const status=(error as any)?.status;if(status===403||status===50001){this.unavailable(id);this.store.retry(id,row.attempts,'Discord permission lost; strategy hidden pending access restoration');this.log('permission_lost',{channelId:id});}else{this.store.retry(id,row.attempts,e.message);this.log('sync_retry',{channelId:id,error:e.message});}}finally{this.running.delete(id);}}
 }
 async handleMessage(channelId:string,messageId?:string){if(messageId){try{await this.api.message(channelId,messageId);}catch{}}this.enqueue(channelId);}
 private unavailable(id:string){this.store.db.prepare("UPDATE strategies SET available=0,json=json_set(json,'$.syncStatus','unavailable') WHERE id=?").run(id);}
}
