function parseStored(value:string):any{try{return JSON.parse(value);}catch(error){throw new Error('Stored playbook record is invalid JSON',{cause:error});}}
import {isVisibleChannel} from '../core/config.js';import {displayTitle,deriveTags} from '../core/projection.js';
import {DatabaseSync} from 'node:sqlite'; import {mkdirSync} from 'node:fs'; import {dirname} from 'node:path';
export class Store {readonly db:DatabaseSync; constructor(path:string){mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS strategies(id TEXT PRIMARY KEY, category_id TEXT NOT NULL, json TEXT NOT NULL, available INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS queue(channel_id TEXT PRIMARY KEY, queued_at TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_attempt INTEGER NOT NULL DEFAULT 0, error TEXT, generation INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, password_version INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS attachment_media(attachment_id TEXT PRIMARY KEY,file TEXT NOT NULL,width INTEGER NOT NULL,height INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attempts(ip TEXT PRIMARY KEY,count INTEGER NOT NULL,window_start INTEGER NOT NULL);`);}
 mediaFor(id:string){const media=this.db.prepare('SELECT file,width,height FROM attachment_media WHERE attachment_id=?').get(id) as {file:string;width:number;height:number}|undefined;return media?{...media,hash:media.file.slice(0,64)}:undefined;}
 rememberMedia(id:string,value:{file:string;width:number;height:number}){this.db.prepare('INSERT INTO attachment_media(attachment_id,file,width,height) VALUES(?,?,?,?) ON CONFLICT(attachment_id) DO UPDATE SET file=excluded.file,width=excluded.width,height=excluded.height').run(id,value.file,value.width,value.height);}
 setMeta(key:string,value:unknown){this.db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,JSON.stringify(value));}
 getMeta<T>(key:string):T|null{const row=this.db.prepare('SELECT value FROM settings WHERE key=?').get(key) as {value:string}|undefined;return row?parseStored(row.value) as T:null;}
 publish(strategy:any){const tx=this.db.prepare('INSERT INTO strategies(id,category_id,json,available,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category_id=excluded.category_id,json=excluded.json,available=1,updated_at=excluded.updated_at');tx.run(strategy.id,strategy.categoryId,JSON.stringify(strategy),1,new Date().toISOString());}
 getStrategy(id:string){const x=this.db.prepare('SELECT json FROM strategies WHERE id=? AND available=1').get(id) as {json:string}|undefined;const strategy=x?parseStored(x.json):null;return strategy&&isVisibleChannel(strategy.sourceName??'')?{...strategy,title:strategy.sourceName?displayTitle(strategy.sourceName):strategy.title,tags:strategy.sourceName?deriveTags(strategy.sourceName):strategy.tags}:null;}
 listStrategies(){return (this.db.prepare("SELECT json FROM strategies WHERE available=1 ORDER BY category_id, json_extract(json,'$.position'),id").all() as {json:string}[]).map(x=>parseStored(x.json)).filter(s=>isVisibleChannel(s.sourceName??'')).map(s=>({...s,title:s.sourceName?displayTitle(s.sourceName):s.title,tags:s.sourceName?deriveTags(s.sourceName):s.tags}));}
 revokeOutOfScope(categoryIds:Set<string>,excludedChannelIds:Set<string>){const all=this.db.prepare('SELECT id,category_id FROM strategies').all() as {id:string;category_id:string}[];for(const x of all)if(!categoryIds.has(x.category_id)||excludedChannelIds.has(x.id))this.db.prepare("UPDATE strategies SET available=0,json=json_set(json,'$.syncStatus','unavailable') WHERE id=?").run(x.id);}
 enqueue(id:string,debounceMs=5000){this.db.prepare("UPDATE strategies SET json=json_set(json,'$.syncStatus','stale') WHERE id=? AND available=1").run(id);this.db.prepare('INSERT INTO queue(channel_id,queued_at,next_attempt,generation) VALUES(?,?,?,1) ON CONFLICT(channel_id) DO UPDATE SET queued_at=excluded.queued_at,next_attempt=excluded.next_attempt,generation=queue.generation+1').run(id,new Date().toISOString(),Date.now()+debounceMs);}
 due(now=Date.now()){return this.db.prepare('SELECT channel_id,attempts,generation FROM queue WHERE next_attempt<=? ORDER BY queued_at').all(now) as {channel_id:string;attempts:number;generation:number}[];}
 markSyncStatus(id:string,generation:number){this.db.prepare("UPDATE strategies SET json=json_set(json,'$.syncStatus',CASE WHEN EXISTS(SELECT 1 FROM queue WHERE channel_id=? AND generation=?) THEN 'current' ELSE 'stale' END) WHERE id=? AND available=1").run(id,generation,id);}
 done(id:string,generation?:number){if(generation!==undefined)this.db.prepare('DELETE FROM queue WHERE channel_id=? AND generation=?').run(id,generation);else this.db.prepare('DELETE FROM queue WHERE channel_id=?').run(id);}
 retry(id:string,attempts:number,error:string){const delay=Math.min(300000,1000*2**Math.min(attempts,8));this.db.prepare('UPDATE queue SET attempts=?,next_attempt=?,error=? WHERE channel_id=?').run(attempts+1,Date.now()+delay,error.slice(0,300),id);}
 close(){this.db.close();}
}
